name: Build All Wheels ARM64

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install System Dependencies (C++, CMake, Crypto)
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential cmake libssl-dev libffi-dev

      - name: Build Wheels dari requirements.txt
        run: |
          # Membuat folder khusus untuk menampung semua hasil compile
          mkdir wheelhouse
          
          # PIP akan membaca file requirements.txt dan menaruh hasilnya di folder wheelhouse
          pip wheel -r requirements.txt -w ./wheelhouse

      - name: Upload Semua File .whl
        uses: actions/upload-artifact@v4
        with:
          name: all-python-wheels-arm64
          path: ./wheelhouse/*.whl
          retention-days: 5
